name = "budgetapp"
main = "src/index.js"
compatibility_date = "2026-06-20"

routes = [
  { pattern = "budget.davidmace.us", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "budget_db"
database_id = "3d6f2446-16c0-4dcc-b766-f9f074a6433e"
